name: CD Fake
on:
  repository_dispatch:
    types:
      - deploy_remoto
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no ambiente
        run: echo "Executando o deploy no ambiente ${{ github.event.client_payload.ambiente }}"
